#pragma checksum "..\..\..\..\AudioMeterControl.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "BA10A32A471D5DA428783821A6AF18ECDBBC3B0F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AudioBit.UI.Infrastructure;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AudioBit.UI {
    
    
    /// <summary>
    /// AudioMeterControl
    /// </summary>
    public partial class AudioMeterControl : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 7 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal AudioBit.UI.AudioMeterControl RootControl;
        
        #line default
        #line hidden
        
        
        #line 393 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border CardBorder;
        
        #line default
        #line hidden
        
        
        #line 401 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.TranslateTransform CardTranslateTransform;
        
        #line default
        #line hidden
        
        
        #line 405 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border CardSurface;
        
        #line default
        #line hidden
        
        
        #line 411 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border CardSheen;
        
        #line default
        #line hidden
        
        
        #line 426 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border CardHoverStroke;
        
        #line default
        #line hidden
        
        
        #line 532 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid MeterPanel;
        
        #line default
        #line hidden
        
        
        #line 563 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform BarScale01;
        
        #line default
        #line hidden
        
        
        #line 568 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform BarScale02;
        
        #line default
        #line hidden
        
        
        #line 573 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform BarScale03;
        
        #line default
        #line hidden
        
        
        #line 578 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform BarScale04;
        
        #line default
        #line hidden
        
        
        #line 583 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform BarScale05;
        
        #line default
        #line hidden
        
        
        #line 588 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform BarScale06;
        
        #line default
        #line hidden
        
        
        #line 593 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform BarScale07;
        
        #line default
        #line hidden
        
        
        #line 598 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform BarScale08;
        
        #line default
        #line hidden
        
        
        #line 603 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform BarScale09;
        
        #line default
        #line hidden
        
        
        #line 608 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform BarScale10;
        
        #line default
        #line hidden
        
        
        #line 613 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform BarScale11;
        
        #line default
        #line hidden
        
        
        #line 618 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform BarScale12;
        
        #line default
        #line hidden
        
        
        #line 623 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform BarScale13;
        
        #line default
        #line hidden
        
        
        #line 629 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform BarScale14;
        
        #line default
        #line hidden
        
        
        #line 634 "..\..\..\..\AudioMeterControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid StaticMeterPanel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.1.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/AudioBit.UI;V0.0.0.0;component/audiometercontrol.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\AudioMeterControl.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.1.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.RootControl = ((AudioBit.UI.AudioMeterControl)(target));
            return;
            case 2:
            
            #line 392 "..\..\..\..\AudioMeterControl.xaml"
            ((System.Windows.Controls.Grid)(target)).Loaded += new System.Windows.RoutedEventHandler(this.RootGrid_OnLoaded);
            
            #line default
            #line hidden
            return;
            case 3:
            this.CardBorder = ((System.Windows.Controls.Border)(target));
            
            #line 396 "..\..\..\..\AudioMeterControl.xaml"
            this.CardBorder.MouseEnter += new System.Windows.Input.MouseEventHandler(this.CardBorder_OnMouseEnter);
            
            #line default
            #line hidden
            
            #line 397 "..\..\..\..\AudioMeterControl.xaml"
            this.CardBorder.MouseLeave += new System.Windows.Input.MouseEventHandler(this.CardBorder_OnMouseLeave);
            
            #line default
            #line hidden
            return;
            case 4:
            this.CardTranslateTransform = ((System.Windows.Media.TranslateTransform)(target));
            return;
            case 5:
            this.CardSurface = ((System.Windows.Controls.Border)(target));
            return;
            case 6:
            this.CardSheen = ((System.Windows.Controls.Border)(target));
            return;
            case 7:
            this.CardHoverStroke = ((System.Windows.Controls.Border)(target));
            return;
            case 8:
            this.MeterPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 9:
            this.BarScale01 = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 10:
            this.BarScale02 = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 11:
            this.BarScale03 = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 12:
            this.BarScale04 = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 13:
            this.BarScale05 = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 14:
            this.BarScale06 = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 15:
            this.BarScale07 = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 16:
            this.BarScale08 = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 17:
            this.BarScale09 = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 18:
            this.BarScale10 = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 19:
            this.BarScale11 = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 20:
            this.BarScale12 = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 21:
            this.BarScale13 = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 22:
            this.BarScale14 = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 23:
            this.StaticMeterPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 24:
            
            #line 710 "..\..\..\..\AudioMeterControl.xaml"
            ((System.Windows.Controls.Slider)(target)).PreviewMouseWheel += new System.Windows.Input.MouseWheelEventHandler(this.VolumeSlider_OnPreviewMouseWheel);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

